### ISSUE TITLE
Should there be more documentation for 3rd party's who intend to use this?

### ISSUE THREAD

**Issue by Lusitaniae** [prometheus/circleci#22]
I'm maintainer for 2 exporters for Apache and PHP-FPM 

Ideally I would be consistent with the official exporters and implement the same CI/CD and release process.

Would be nice if you would document the details that non officials exporters would need to implement this.

So far, it seems I'd need to override the default organization parameters from the orb so that the final .cirlceci.yml would look like. Since I'm not active user of Circle CI having all this documented in advnace would make my life much easier.

It would probably be good to document all the env variables needed to make this work.

(Docker/Quay users, etc)

```
      - prometheus/publish_master:
          context: org-global
          docker_hub_organization: lusotycoon
          quay_io_organization: lusitaniae
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - prometheus/publish_release:
          context: org-global
          docker_hub_organization: lusotycoon
          quay_io_organization: lusitaniae
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
```
